[tools]
golang = "1.23.3"
golangci-lint = "1.56.2"
shellcheck = "0.9.0"
nodejs = "20.11.1"
shfmt = "3.7.0"
vale = "3.3.0"

[tasks.build]
depends = ['build-assets']
env = { CGO_ENABLED = '0', GOOS = 'linux', GOARCH = 'arm64' }
run = "go build -ldflags '-w' -o samesite"

[tasks.build-assets]
run = "npm run build"

[tasks.run]
depends = ['build-assets']
sources =[
  '**/*.{tmpl,go}',
  'src/**/*',
  'package-lock.json',
]
run = "go run ."

[tasks.watch]
run = "mise watch -r run"

[tasks.deploy]
depends = ['build']
run = """
#!/usr/bin/env bash

set -xeuf -o pipefail

HOST="i.jarv.org"

ssh root@$HOST "sudo systemctl stop samesite.service"
scp samesite root@$HOST:/opt/samesite/samesite
ssh root@$HOST "sudo systemctl start samesite.service"
rm -f samesite
"""
